"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const industry = require("../game/industry");
const valuation = require("../game/ai/valuation");
const source = fs.readFileSync(path.join(__dirname, "ai-controller.js"), "utf8");
const start = source.indexOf("function getAiLaunchPaymentCost(");
const end = source.indexOf("function scoreAiLaunchPaymentCost(", start);
assert.ok(start >= 0 && end > start);
let current;
const resolve = Function("industry", "ai", "getCurrentPlayer", `return (${source.slice(start, end).trim()});`)(industry, { valuation }, () => current);
const player = label => ({ initialSelection: { industry: { id: `industry:${label}`, label } }, industryAlienLabPanels: { blue: true, yellow: true, pink: true } });
current = player("作弊实验室");
assert.deepEqual(resolve(), { credits: 1 }, "permanent lab panel must discount the AI default cost");
current.industryAlienLabPanels.blue = false;
assert.deepEqual(resolve(), { credits: 1 }, "cheat lab stays discounted even if its stored panel is false");
const lab = player("异星实验室");
assert.deepEqual(resolve({}, lab), { credits: 1 });
lab.industryAlienLabPanels.blue = false;
assert.deepEqual(resolve({}, lab), { credits: 2 }, "flipped normal lab loses its discount");
assert.deepEqual(resolve({}, player("寰宇超动力")), { credits: 2 });
const explicit = { cost: { energy: 1 } };
const before = structuredClone(explicit);
assert.deepEqual(resolve(explicit), { energy: 1 });
assert.deepEqual(explicit, before, "resolving cost must not mutate an effect");
assert.deepEqual(resolve({ skipCost: true, cost: { energy: 2 } }), {});
assert.deepEqual(resolve({ cost: {} }), {}, "an explicit zero cost must remain zero");
assert.deepEqual(resolve({ options: { skipCost: true } }), {});
console.log("ai-launch-cost.test.js: all tests passed");
